import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";

import authenticate from "@/lib/server/auth/authenticate";


import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let initialUser = null;
  try {
    initialUser = await authenticate();
  } catch (er) {
    initialUser = null;
  }

  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        {/* <AuthProvider initialUser={initialUser}> */}
          {children}
          <Toaster position="center" />
        {/* </AuthProvider> */}
      </body>
    </html>
  );
}
