import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import {cookies} from "next/headers"
import {jwtDecode} from "jwt-decode";
import { AuthProvider } from "#root/context/AuthContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const token = (await cookies()).get("token")?.value;

  let initialUser = null;

  if (token) {
    const decodedUser = jwtDecode(token);
    initialUser = decodedUser;
  }
  
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <AuthProvider initialUser={initialUser}>
          {children}
          <Toaster position="center" />
        </AuthProvider>
      </body>
    </html>
  );
}
